### ISSUE TITLE
Not able to run the neurips2019 code

### ISSUE THREAD

**Issue by Kennard123661** [HumanCompatibleAI/human_aware_rl#14]
Hi! Thank you for the amazing work!

I am not able to run your neurips2019 branch, it seems there's some differences between the data keys and the expected data keys:
![image](https://user-images.githubusercontent.com/17818981/96209717-da81f280-0fa2-11eb-859b-87e3ac996b32.png)

**Comment by micahcarroll** [comment]
I will be looking over this issue this weekend and get back to you!

**Comment by Kennard123661** [comment]
Hi @micahcarroll Thanks for the prompt reply! If possible, could I have the training data and the testing data in the format of the data in master branch? it would be very helpful! Thank you!

**Comment by Kennard123661** [comment]
Hi @micahcarroll , I found the issue, the overcooked_ai git submodule needs to be rollbacked to the previous version, the current version in neurips2019 is incompatible. After I rolled back it works!

Thanks!

**Comment by micahcarroll** [comment]
Thanks for the update! Would you mind sharing which overcooked_ai commit you ended up using?

**Comment by Kennard123661** [comment]
Hi @micahcarroll , I used the overcooked_ai commit here https://github.com/HumanCompatibleAI/overcooked_ai/tree/6eaceb0a9a2501f1b9fccbf4c7016d6662ed1108

Thank you!
