### ISSUE TITLE
Error installing master

### ISSUE THREAD

**Issue by HelloN00bman** [HumanCompatibleAI/human_aware_rl#19]
Hi! I'm trying to install from master and have been having some issues running the testing scripts. As far as I can tell this issue is not covered in the troubleshooting section of the README.

I am following the installation instructions and getting ValueErrors during the ppo_rllib_tests.py script. I have replicated this problem on a MacOS (Catalina), and Ubuntu 18. 

I've also attached the output from ./run_tests.sh to this issue. 

Let me know if you need any more info! Thanks!

[test_out.txt](https://github.com/HumanCompatibleAI/human_aware_rl/files/7245840/test_out.txt)

**Comment by micahcarroll** [comment]
Unless you need this done faster, I will probably get to this sometime next week. Let me know if sooner would be better!

**Comment by HelloN00bman** [comment]
Thanks, Micah! For now I'll start with the neurips2019 branch, but it would be great to be able to use the main branch :).

Looking forward to it!

**Comment by jyp0802** [comment]
Hi! Are there any updates on this issue?

**Comment by micahcarroll** [comment]
The issue should be fixed with the latest commit! Sorry for the wait
