### ISSUE TITLE
Add testing for pretrained models

### ISSUE THREAD

**Issue by alexlichtenstein** [HumanCompatibleAI/human_aware_rl#28]
Things to do:
- [x] Train models for the 5 classic layouts
- [x] Verify that the agents converge to good performance
- [x] Add tests for loading pre-trained models and for the resume function 
- [x] Update sample training script (add training configurations for the 5 classic layouts)
- [x] Add documentation
- [x] Make a PR from new branch to master

**Comment by micahcarroll** [comment]
We should add all issues [here too](https://github.com/orgs/HumanCompatibleAI/projects/4) to keep things organized! :)

**Comment by alexlichtenstein** [comment]
> We should add all issues [here too](https://github.com/orgs/HumanCompatibleAI/projects/4) to keep things organized! :)

done
