### ISSUE TITLE
ImportError while running the behavior_cloning_tf2_test.py 

### ISSUE THREAD

**Issue by abhilashrj** [HumanCompatibleAI/human_aware_rl#8]
ImportError: cannot import name 'EVENT_TYPES' from 'overcooked_ai_py.mdp.overcooked_mdp' 
There is no EVENT_TYPES variable declared in the file human_aware_rl\overcooked_ai\overcooked_ai_py\mdp\overcooked_mdp.py.

**Comment by mesutyang97** [comment]
Hi,
Thanks for reaching out. [It should be there](https://github.com/HumanCompatibleAI/overcooked_ai/blob/master/src/overcooked_ai_py/mdp/overcooked_mdp.py). Make sure you have pulled the latest `master`

Let me know if you have further questions

**Comment by abhilashrj** [comment]
Thanks much for the quick reply!
